Repository Annie0121/weather, pull requests merged in 2024-07, with the labels that each got.

#1 Feat: main.py routing and MVC
  .gitignore
  Readme.md
  controllers/cityname_controller.py
  main.py
  models/CityName.py
Labels: documentation, API

#4 feat: city names and towns name
  controllers/cityname_controller.py
  docs/city_towns.json
  models/CityName.py
Labels: API

#10 fix: frontend file path error and city_name API Swagger documents
  controllers/cityname_controller.py
  main.py
  static/index.html
Labels: documentation, API

#9 fix the confilct brtween main and docker-build
  Dockerfile
  controllers/daily_weather_controller.py
  docker-compose.yml
  models/CityName.py
  requirements.txt
Labels: documentation, API

#13 fix, daily weather api to meet the requirement
  controllers/daily_weather_controller.py
  docker-compose.yml
  main.py
Labels: API

#17 fix: static files path error and load_dotenv API key missing
  controllers/daily_weather_controller.py
  main.py
  static/city.html
  static/index_background.jpg
Labels: bug

#20 feat: weekly_city_weather API 某城市未來一週天氣
  controllers/weekly_city_weather_controller.py
  main.py
  requirements.txt
Labels: API

#22 hotFix: weekly_city_weather API
  controllers/weekly_city_weather_controller.py
Labels: bug

#24 fix: weekly city weather Wx format
  controllers/weekly_city_weather_controller.py
Labels: bug, API

#32 Fix: weekly_city_weather_controller arrange_weather_data method
  controllers/weekly_city_weather_controller.py
Labels: bug, API
